name: aviasoul_front
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  reactive_forms: ^16.1.1
  freezed: ^2.4.5
  shared_preferences: ^2.2.2
  bloc: ^8.1.2
  build_runner: ^2.4.6
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  badges: ^3.1.2
  top_snackbar_flutter: ^3.1.0
  syncfusion_flutter_charts: 22.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/

